//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobReferralapplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class jobdescription
    {
        [Key]
        public int jobid { get; set; }
        [Required]
        public string jobdescription1 { get; set; }
        [Required]
        public Nullable<int> requiredexp { get; set; }
        [Required]
        public int noticeperiod { get; set; }
        [Required]
        public int primaryskills { get; set; }
        public string additional_skills { get; set; }
        public string joblocation { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
