//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobReferralapplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobreferenceEntities2 : DbContext
    {
        public JobreferenceEntities2()
            : base("name=JobreferenceEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<jobdescription> jobdescriptions { get; set; }
        public virtual DbSet<referencereg> referenceregs { get; set; }
        public virtual DbSet<referredjob> referredjobs { get; set; }
        public virtual DbSet<skill> skills { get; set; }
    }
}
